# This file is generated by [bash-completor](https://github.com/adoyle-h/bash-completor/tree/v0.2.0). Do not modify it manually.
#
# [Usage]
# Put "source display-brightness-tool.bash" in your bashrc.
#
# If you want to debug the completion.
# Search '# Uncomment this line for debug' line in this file.
#
# [Update Script]
# bash-completor -c ./display-brightness-tool.completor.bash
#
# [Authors]
# IsaacST08 (isaacshiellsthomas@me.com)

# shellcheck disable=2207
# editorconfig-checker-disable

_display_brightness_tool_comp_cmd_opts=( -h --help --version -d --display -c --clear-cache -a --action -v --value -u --update -t --update-threshold -V --verbose )


_display_brightness_tool_comp_reply_dirs ()
{
    local IFS=$'\n';
    compopt -o nospace -o filenames;
    COMPREPLY=($(compgen -A directory -- "$cur"))
}

_display_brightness_tool_comp_reply_files ()
{
    local IFS=$'\n';
    compopt -o nospace -o filenames;
    COMPREPLY=($(compgen -A file -- "$cur"))
}

_display_brightness_tool_comp_reply_files_in_pattern ()
{
    compopt -o nospace -o filenames;
    local path;
    while read -r path; do
        if [[ $path =~ $1 ]] || [[ -d $path ]]; then
            COMPREPLY+=("$path");
        fi;
    done < <(compgen -A file -- "$cur")
}

_display_brightness_tool_comp_reply_list ()
{
    local IFS=', ';
    local array_list="" array_name;
    for array_name in $@;
    do
        array_list="$array_list \${${array_name}[*]}";
    done;
    array_list="${array_list[*]:1}";
    IFS=$'\n'' ';
    eval "COMPREPLY=( \$(compgen -W \"$array_list\" -- \"\$cur\") )"
}

_display_brightness_tool_comp_reply_words ()
{
    local IFS=$'\n';
    COMPREPLY=($(IFS=', ' compgen -W "$*" -- "${cur#=}"))
}

_display_brightness_tool_comp_reply_set() {
  local IFS=', '
  local array_list="" array_name
  # shellcheck disable=2068
  for array_name in $@; do
    array_list="$array_list \${_display_brightness_tool_comp_var_${array_name}[*]}"
  done
  array_list="${array_list[*]:1}"

  IFS=$'\n'' '
  eval "COMPREPLY=( \$(compgen -W \"$array_list\" -- \"\$cur\") )"
}

_display_brightness_tool_completions() {
  COMPREPLY=()
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}

  # Uncomment this line for debug
  # echo "[COMP_CWORD:$COMP_CWORD][cur:$cur][prev:$prev][WORD_COUNT:${#COMP_WORDS[*]}][COMP_WORDS:${COMP_WORDS[*]}]" >> bash-debug.log

  # Enter the cmd completion
  if [[ ${cur:0:1} == [-+] ]]; then
    # rely options of command
    _display_brightness_tool_comp_reply_list _display_brightness_tool_comp_cmd_opts
  elif [[ ${prev:0:1} == [-+] ]]; then
    case "${prev}" in
      # rely the value of command option
      -d) _display_brightness_tool_comp_reply_words 'all,oled,non-oled' ;;
      --display) _display_brightness_tool_comp_reply_words 'all,oled,non-oled' ;;
      -a) _display_brightness_tool_comp_reply_words 'set,increase,decrease,save,restore,dim,undim' ;;
      --action) _display_brightness_tool_comp_reply_words 'set,increase,decrease,save,restore,dim,undim' ;;
      -v)  ;;
      --value)  ;;
      -t)  ;;
      --update-threshold)  ;;
      *) _display_brightness_tool_comp_reply_words 'set increase decrease save restore dim undim' ;;
    esac
  else
    # rely the argument of command
    _display_brightness_tool_comp_reply_words 'set increase decrease save restore dim undim'
  fi
}

complete -F _display_brightness_tool_completions -o bashdefault display-brightness-tool
# vi: sw=2 ts=2
